### ISSUE TITLE
I can't delete a redundant member

### ISSUE THREAD

**Issue by isaac-gofa** [onepub-dev/onepub#291]
![image](https://user-images.githubusercontent.com/126567837/223681779-a040d2a6-5341-4014-93b3-44b841536c52.png)
![image](https://user-images.githubusercontent.com/126567837/223681633-318d1a3c-4a0b-4fbd-b503-07a4a951ec5a.png)

**Comment by bsutton** [comment]
Thanks for reporting the issue.

We are aware of the issue and if all goes well, we release a fix tomorrow.

**Comment by bsutton** [comment]
There is a new menu item on the Member view 'Remove Member'. This correctly removes a member from your organisation.
This replaced the previous 'Delete' item, which conveyed the wrong semantics (we are just detaching the member from your organisation as opposed to actually deleting them as they may belong to other organisations).
Otherwise this work is complete and deployed.

I will close this issue out, but if you have any problems feel free to re-open.
